# -*- coding: utf-8 -*-
"""Merger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Au5xqPCTWvedqCW-YKcvU-1FlQWiKqdM
"""

import os
import zipfile
import pandas as pd
import random
from collections import Counter

zip_path = "Merger.zip"
extract_path = "."

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

csv_folder = os.path.join("Merger", "All_submisions")

votes = {}

for filename in os.listdir(csv_folder):
    if filename.endswith(".csv"):
        df = pd.read_csv(os.path.join(csv_folder, filename))
        for _, row in df.iterrows():
            image_id = row["image_id"]
            label = row["label"]
            votes.setdefault(image_id, []).append(label)

#Facem vot majoritar
results = []
for image_id, label_list in votes.items():
    count = Counter(label_list)
    top_freq = count.most_common(1)[0][1]
    top_labels = [label for label, freq in count.items() if freq == top_freq]
    chosen = random.choice(top_labels)
    results.append({"image_id": image_id, "label": chosen})

output_df = pd.DataFrame(results)
output_df.to_csv("majority_voted_labels.csv", index=False)
